### ISSUE TITLE
Issue compiling the library

### ISSUE THREAD

**Issue by Uzaaft** [Igosuki/signalr-rs#1]
I'm having issues compiling the library while implementing the signal-rs library into my project. 
The library also fails to compile whenever I try to compile it at it's own.
<details>
<summary>Getting the error:</summary> 

```
error[E0554] `#![feature]` may not be used on the stable release channel
 --> /Users/uzaaft/.cargo/registry/src/github.com-1ecc6299db9ec823/signalr_rs-0.1.4/src/lib.rs:1:1
  |
1 | #![feature(try_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `signalr_rs`

To learn more, run the command again with --verbose.
[Finished running. Exit status: 101]
```
</details>
Attempting to compile it with:  

macOS Monterey beta  
cargo 1.53.0 (4369396ce 2021-04-27)   
rustc 1.53.0 (53cb7b09b 2021-06-17)   
Do tell if more information is needed.

**Comment by Igosuki** [comment]
Features are only available in nightly, can you use the nightly channel ?

**Comment by Uzaaft** [comment]
Compiling with nightly fails with Error E0432.
Error message:
<details>
<summary>Getting the error:</summary> 

```
   Compiling signalr_rs v0.1.4
error[E0432]: unresolved import `std::option::NoneError`
  --> /Users/uzaaft/.cargo/registry/src/github.com-1ecc6299db9ec823/signalr_rs-0.1.4/src/hub/client.rs:21:5
   |
21 | use std::option::NoneError;
   |     ^^^^^^^^^^^^^^^^^^^^^^ no `NoneError` in `option`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `signalr_rs`

To learn more, run the command again with --verbose.
```
</details>
--verbose did not return any useful information.   

Using:  
cargo 1.54.0-nightly (44456677b 2021-06-12)  
rustc 1.55.0-nightly (406d4a9cc 2021-06-21)

**Comment by Igosuki** [comment]
I started using actix4 in all my projects and had a branch ready for this crate. I merged the actix4 branch in master let me know if that's good enough for you.

**Comment by Uzaaft** [comment]
Thank you! I'm able to compile the library now with the stable channel. Appreciate the help!

**Comment by Igosuki** [comment]
No worries, as soon as actix 4 is out of beta I will make a release.
Let me know if there are any more changes you need.
