### ISSUE TITLE
client.rs error E0432 use std::option::NoneError

### ISSUE THREAD

**Issue by iantr** [Igosuki/signalr-rs#4]
I'm unable to compile the signalr-rs crate on either Windows or Linux, using either the stable or nightly build of the rust tooling. I always get this error:

error[E0432]: unresolved import `std::option::NoneError`
  --> /home/iantr/.cargo/registry/src/github.com-1ecc6299db9ec823/signalr_rs-0.1.4/src/hub/client.rs:21:5
   |
21 | use std::option::NoneError;
   |     ^^^^^^^^^^^^^^^^^^^^^^ no `NoneError` in `option`

**Comment by Igosuki** [comment]
Sorry the crate was not published for a while, thanks for catching this. You can now use 0.2.0 which uses actix 4 and has more goodies.
