### ISSUE TITLE
Can't get a basic client to communicate with a SignalR server

### ISSUE THREAD

**Issue by iantr** [Igosuki/signalr-rs#6]
I created a basic SignalR server following Microsoft's walkthrough here: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr

It was trivial to create a C# console client to talk to it. I'm trying to do the same with signalr-rs. I'm having issues getting the Rust signalr-rs code to connect.

I would be happy to contribute working code (server and client) if you like, once I can get the Rust client working. 

This is the working C# for the console client:

    public class SignalRConnection
    {
        public async void Start()
        {
            var url = "https://localhost:5001/chathub"; 

            var hubConnection = new HubConnectionBuilder()
                .WithUrl(url)
                .WithAutomaticReconnect()
                .Build();

            // Avoid certificate errors for now
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

            // receive a message from the hub
            hubConnection.On<string, string>("ReceiveMessage", (user, message) => OnReceiveMessage(user, message));

            var task = hubConnection.StartAsync();

            task.Wait();

            // send a message to the hub
            await hubConnection.InvokeAsync("SendMessage", "ConsoleApp", "Message from the console app");
        }

        private void OnReceiveMessage(string user, string message)
        {
            Console.WriteLine($"{user}: {message}");
        }
    }

This is my in-progress but not working Rust "equivalent":

#[actix_rt::main]
async fn main() -> io::Result<()> {
    env_logger::init();

    println!("SignalR Console Rust Client");

    let url = Url::parse("https://localhost:5001/");

    let hub = "chathub";
    let handler = Box::new(ChatHubHandler { hub: hub.to_string() });

    // Set up the SSL connector so verification can be turned off for now
    let mut builder = SslConnector::builder(SslMethod::tls()).unwrap();
    builder.set_verify(openssl::ssl::SslVerifyMode::NONE); // avoid certificate errors for now
    let connector = builder.build();

    let client = HubClientBuilder::with_hub_and_url(hub, url.unwrap())
        .ssl_connector(connector)
        .start_supervised(handler)
        .await;

    println!("Client started");

    match client {
        Ok(addr) => {
            addr.do_send(HubQuery::new(
                hub.to_string(),
                "SendMessage".to_string(),
                vec!["Rust Console App"],
                "Message from the Rust console app".to_string(),
            ));
        }
        Err(e) => {
            println!("Hub client error : {:?}", e);
            System::current().stop();
        }
    }

    actix_rt::signal::ctrl_c().await
}

I get this output:

SignalR Console Rust Client
Client started
Hub client error : ParseError(Error("expected value", line: 1, column: 1))

I'd be happy to upload the server code in a PR. It's just the code from Microsoft's SignalR example.

**Comment by Igosuki** [comment]
Sure, put it in an example so I can review it

**Comment by iantr** [comment]
Thanks for taking a look! I hope this example helps your project once the issues in my Rust client are worked out. You can see my example added to my fork of the project (I was not able to push to your project and so I let the tooling create a fork).  You can see the sample here: 
https://github.com/iantr/signalr-rs/tree/iantr/C%23_Example/examples/BlazorWebAssemblySignalRApp

**Comment by Igosuki** [comment]
So after spending about an hour getting familiar with C# and your example, it seems the blazor server doesn't accept the same kind of connection handling as the SignalR configured on Bittrex servers for which the example still works out of the box.

**Comment by Igosuki** [comment]
So, as you can see the UI client on port 5001 does something quite different than the HubClient does, it does a post request for negotiation and then upgrades the conn to a websocket.
While the Hub Client in signalr-rs does a GET request for negotiation, on another endpoint.
So I suggest you first find how to parameterize the server properly so that negotiation can be done on GET requests (maybe it's the 5000 port by default ?).
I'll be happy to document how to start a C# project compatible with this library once you do.

**Comment by iantr** [comment]
Thanks very much for your efforts, Guillaume! I'll give things a try - this helps a lot.

Cheers

Ian

________________________________

**Comment by Igosuki** [comment]
@iantr Have you been able to figure it out ?

**Comment by iantr** [comment]
Thanks for getting back to me, Guillaume. I've moved to Socket.IO for WebSocket stuff since I needed a protocol that was more open. I found a Rust library for that which I've been able to get working. I'm a total Microsoft guy I have to admit but in searching around it seemed like there was less industry support for SignalR. Socket.IO does some nice things such as start with HTTP long polling and then transitioning to WebSockets if possible. That's a durable approach that is important for my needs. I can't tell what Microsoft is doing under the covers - I'm not sure what the spec is. I also know the company I work for (Absolute Software) wouldn't be that keen on adopting a Microsoft-only protocol.

Thanks very much for getting back to me.

Cheers!


Ian

________________________________

**Comment by Igosuki** [comment]
Well yeah SignalR is just like Socket.IO in that it tries to build a bidirectionnal technology that can work in any environment using both XHRs and WS, Socket was always going to be leaner and closer to what the browser does, SignalR seems to be a bit too integrated with Microsoft's stack.
